<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>prep</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChannelsPublisher.Prep\ChannelsPublisher.Prep.csproj" />
  </ItemGroup>
</Project>
